apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    labels:
        component: crd
        app: agones
        chart: agones-1.25.0-dev
        release: agones-manual
        heritage: Helm
    name: gameserverallocationpolicies.multicluster.agones.dev
spec:
    group: multicluster.agones.dev
    names:
        kind: GameServerAllocationPolicy
        plural: gameserverallocationpolicies
        shortNames:
            - gsap
    scope: Namespaced
    versions:
        - name: v1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  description: "GameServerAllocationPolicy is the Schema for the gameserverallocationpolicies API."
                  type: object
                  properties:
                      spec:
                          description:
                              "GameServerAllocationPolicySpec defines the desired state of GameServerAllocationPolicy. More info:
                              https://agones.dev/site/docs/reference/agones_crd_api_reference/#multicluster.agones.dev/v1.GameServerAllocationPolicy"
                          type: object
                          required:
                              - priority
                              - weight
                          properties:
                              priority:
                                  format: int32
                                  minimum: 0
                                  type: integer
                              weight:
                                  format: int64
                                  minimum: 0
                                  type: integer
                              connectionInfo:
                                  type: object
                                  required:
                                      - namespace
                                  properties:
                                      clusterName:
                                          type: string
                                      allocationEndpoints:
                                          items:
                                              type: string
                                          type: array
                                          minItems: 1
                                      secretName:
                                          type: string
                                      namespace:
                                          type: string
                                      serverCa:
                                          type: string
                                          format: byte
